// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANYSImCkhS7T18aBN0cKb1Qinh2sZHXUw',
    appId: '1:900354422243:web:a2268c737bca0fa69e1cd6',
    messagingSenderId: '900354422243',
    projectId: 'pharmmatch-edcef',
    authDomain: 'pharmmatch-edcef.firebaseapp.com',
    storageBucket: 'pharmmatch-edcef.appspot.com',
    measurementId: 'G-M42NM644S2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIH2AU0OkTm78g7J2QQrAZ_RkPBL1dHXU',
    appId: '1:900354422243:android:26e0c6ba2dc149e39e1cd6',
    messagingSenderId: '900354422243',
    projectId: 'pharmmatch-edcef',
    storageBucket: 'pharmmatch-edcef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIYGP4tGKV8T-sH2klmT9n3OFwnnohrSs',
    appId: '1:900354422243:ios:0eaa7899b0e2675c9e1cd6',
    messagingSenderId: '900354422243',
    projectId: 'pharmmatch-edcef',
    storageBucket: 'pharmmatch-edcef.appspot.com',
    iosClientId: '900354422243-9st2v2h6r72b98tq9flgmh7rrlda855b.apps.googleusercontent.com',
    iosBundleId: 'com.example.pharmmatchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIYGP4tGKV8T-sH2klmT9n3OFwnnohrSs',
    appId: '1:900354422243:ios:0eaa7899b0e2675c9e1cd6',
    messagingSenderId: '900354422243',
    projectId: 'pharmmatch-edcef',
    storageBucket: 'pharmmatch-edcef.appspot.com',
    iosClientId: '900354422243-9st2v2h6r72b98tq9flgmh7rrlda855b.apps.googleusercontent.com',
    iosBundleId: 'com.example.pharmmatchApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANYSImCkhS7T18aBN0cKb1Qinh2sZHXUw',
    appId: '1:900354422243:web:a4f30916e019d54b9e1cd6',
    messagingSenderId: '900354422243',
    projectId: 'pharmmatch-edcef',
    authDomain: 'pharmmatch-edcef.firebaseapp.com',
    storageBucket: 'pharmmatch-edcef.appspot.com',
    measurementId: 'G-CSZ5C6DDC0',
  );

}